Code/CustomerComplaintsSystem/Neusoft.CCS.WebUI/Areas/CHS/Controllers/CustomerComplaintController.cs
using Neusoft.CCS.Services.Interfaces;
using Neusoft.CCS.Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Neusoft.CCS.WebUI.Areas.CHS.Controllers
{
    public class CustomerComplaintController : Controller
    {
        //
        // GET: /CHS/CustomerComplaint/

        public ActionResult Index()
        {
            var tmpService = DI.SpringHelper.GetObject<IComplaintService>("ComplaintService").GetAllBusinesses();
            if (tmpService.IsSuccess)
                return View("CreateComplaintView", tmpService.AllBusinesses);
            else
            {
                ViewBag.ErrorMessage = tmpService.ErrorMessage;
                return View("ErrorView");
            }
        }
        /// <summary>
        /// 发起网络投诉
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateComplaint(CreateComplaintViewModel request)
        {
            request.Date = DateTime.Now;
            var tmpService = DI.SpringHelper.GetObject<IComplaintService>("ComplaintService").CreateComplaint(request);
            // return View(tmpService.NotArchivedComplaint);
            var businessService = DI.SpringHelper.GetObject<IComplaintService>("ComplaintService").GetAllBusinesses();
            if (businessService.IsSuccess)
                return View("CreateComplaintView", businessService.AllBusinesses);
            else
            {
                ViewBag.ErrorMessage = tmpService.ErrorMessage;
                return View("ErrorView");
            }
        }

        public ActionResult SearchComplaintByUser()
        {
            return View("SearchComplaintByUserOverView");
        }

        /// <summary>
        /// 根据客户获取所有投诉案件
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult GetComplaintByUser(string name, string phone, string email)
        {
            var tmpService = DI.SpringHelper.GetObject<IComplaintService>("ComplaintService").GetComplaintByUser(name, phone, email);
            if (tmpService.IsSuccess)
                return View("SearchComplaintByUserOverView", tmpService.ComplaintOverView);
            else
            {
                ViewBag.ErrorMessage = tmpService.ErrorMessage;
                return View("ErrorView");
            }
                
        }

        /// <summary>
        /// 查看详细投诉处理结果
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public ActionResult GetComplaintDetailByID(string ID)
        {
            var tmpService = DI.SpringHelper.GetObject<IComplaintService>("ComplaintService").GetComplaintDetailByID(ID);
            if (tmpService.IsSuccess)
            {
                return View("ComplaintHandlingDetailView", tmpService.CaseDetail);
            }
            else
            {
                ViewBag.ErrorMessage = tmpService.ErrorMessage;
                return View("ErrorView");
            }
        }

        /// <summary>
        /// 保存解决方案
        /// </summary>
        /// <param name="ID"></param>
        /// <param name="Solution"></param>
        /// <returns></returns>
        public ActionResult SaveSolution(string ID, string Solution)
        {
            var tmpService = DI.SpringHelper.GetObject<IComplaintService>("ComplaintService").SaveSolution(ID, Solution);
            if (tmpService.IsSuccess)
                return View();
            else
            {
                ViewBag.ErrorMessage = tmpService.ErrorMessage;
                return View("ErrorView");
            }
        }

        /// <summary>
        /// 完成案件
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public ActionResult FinishCase(string ID)
        {
            var tmpService = DI.SpringHelper.GetObject<IComplaintService>("ComplaintService").FinishCase(ID);
            if (tmpService.IsSuccess)
                return View();
            else
            {
                ViewBag.ErrorMessage = tmpService.ErrorMessage;
                return View("ErrorView");
            }
        }
    }
}

Code/CustomerComplaintsSystem/Neusoft.CCS.WebUI/Areas/CHS/Views/CustomerComplaint/ComplaintHandlingDetailView.cshtml
@{
    ViewBag.Title = "详细投诉处理结果";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}
@section title{
    详细投诉处理结果
}
@model Neusoft.CCS.Services.ViewModels.ComplaintHandlingDetailInfoViewModel


<h2>详细投诉处理结果</h2>

@if(Model!= null && Model.BasicInfo!= null)
{
 <table border="1px" bordercolor="#000000" cellspacing="0px" style="border-collapse:collapse">
        <tr>
            <td>
                <strong>姓名</strong>
            </td>
            <td>
               @Model.BasicInfo.ComplainerName
            </td>
            <td>
                <strong>电话</strong>
            </td>
            <td>
               @Model.BasicInfo.Phone
            </td>
            <td>
                <strong>Email</strong>
            </td>
            <td>
                 @Model.BasicInfo.Email
            </td>
        </tr>
        <tr>
             <td>
                <strong>投诉方式</strong>
            </td>
            <td>
                 @Model.BasicInfo.Way
            </td>
            <td>
                <strong>投诉地域</strong>
            </td>
            <td>
                 @Model.BasicInfo.Area
            </td>
            <td>
                <strong>投诉类别</strong>
            </td>
            <td>
                 @Model.BasicInfo.Class
            </td>
        </tr>
        <tr>
            <td>
                <strong>投诉时间</strong>
            </td>
            <td>
                @Model.BasicInfo.Date.ToShortDateString()
            </td>
            <td>
                <strong>开始受理时间</strong>
            </td>
            <td>
                @if(Model.StartTime.Year>1)
                {
                  @Model.StartTime.ToShortDateString()
                }
            </td>
            <td>
                <strong>完成受理时间</strong>
            </td>
            <td>
                @if (Model.EndTime.Year > 1)
                {
                @Model.EndTime.ToShortDateString()
                }
            </td>
        </tr>
        <tr>
           <td>
                <strong>客户问题描述</strong>
           </td>
           <td colspan="5">
                @Model.Describe
           </td>
        </tr>
        <tr>
           <td>
                <strong>解决方案</strong>
           </td>
           <td colspan="5">
                @Model.Solution
           </td>
        </tr>
        <tr>
           <td>
                <strong>处理过程</strong>
           </td>
           <td colspan="5">
                @Model.Process
           </td>
        </tr>
    </table>
}

Code/CustomerComplaintsSystem/Neusoft.CCS.WebUI/Areas/CHS/Views/CustomerComplaint/CreateComplaintView.cshtml
@{
    ViewBag.Title = "发起投诉";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}
@section title{
    发起投诉
}
@model Neusoft.CCS.Services.ViewModels.CreateComplaintViewModel

@{
    List<SelectListItem> items = new List<SelectListItem>();
    if(Model.Businesses != null)
    {
        foreach (var item in Model.Businesses)
        {
            items.Add(new SelectListItem(){ Text =item, Value = item});
        }
    }
    Model.Way = "网上投诉";
  }

<h2>发起投诉</h2>
@using (Html.BeginForm("CreateComplaint","CustomerComplaint")) {
    <table>
        <tr>
            <td>
                <strong>姓名：</strong>
                @Html.HiddenFor(model => model.Way, "网上投诉")
            </td>
            <td>
                
                @Html.EditorFor(model => model.Cmp_Name)
            </td>
            <td>
                <strong>Email：</strong>
            </td>
            <td>
                @Html.EditorFor(model => model.Email)
            </td>
        </tr>
        <tr>
            <td>
                <strong>投诉地域：</strong>
            </td>
            <td>
                @Html.EditorFor(model => model.Cmp_Area)
            </td>
            <td>
                <strong>投诉类别：</strong>
            </td>
            <td>
                @Html.DropDownListFor(model => model.Class, items);
            </td>
        </tr>
        <tr>
            <td>
                <strong>手机号码：</strong>
            </td>
            <td>
                @Html.EditorFor(model => model.Phone)
            </td>
            <td>
                <strong>问题描述：</strong>
            </td>
            <td>
                @Html.TextAreaFor(model => model.Describe)
            </td>
        </tr>
    </table>
    <input id="btn_CreateComplaint" type ="submit" value="提交" />
}

Code/CustomerComplaintsSystem/Neusoft.CCS.WebUI/Areas/CHS/Views/CustomerComplaint/SearchComplaintByUserOverView.cshtml
@{
    ViewBag.Title = "查看投诉处理结果";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}
@section title{
    查看投诉处理结果
}
@model List<Neusoft.CCS.Services.ViewModels.RetrieveComplaintInfoByUserViewModel>


<h2>查看投诉处理结果</h2>
@using (Html.BeginForm("GetComplaintByUser", "CustomerComplaint"))
{
    <table>
        <tr>
            <td>
                <strong>姓名</strong>
            </td>
            <td>
                @Html.TextBox("name")
            </td>
            <td>
                <strong>电话</strong>
            </td>
            <td>
                @Html.TextBox("phone")
            </td>
            <td>
                <strong>Email</strong>
            </td>
            <td>
                @Html.TextBox("email")
            </td>
        </tr>
    </table>@*
    <table>
        <tr>
            <td>
                <strong>姓名：</strong>
                @Html.HiddenFor(model => model.Way, "网上投诉")
            </td>
            <td>
                
                @Html.EditorFor(model => model.Cmp_Name)
            </td>
            <td>
                <strong>Email：</strong>
            </td>
            <td>
                @Html.EditorFor(model => model.Email)
            </td>
        </tr>
        <tr>
            <td>
                <strong>投诉地域：</strong>
            </td>
            <td>
                @Html.EditorFor(model => model.Cmp_Area)
            </td>
            <td>
                <strong>投诉类别：</strong>
            </td>
            <td>
                @Html.DropDownListFor(model => model.Class, items);
            </td>
        </tr>
        <tr>
            <td>
                <strong>手机号码：</strong>
            </td>
            <td>
                @Html.EditorFor(model => model.Phone)
            </td>
            <td>
                <strong>问题描述：</strong>
            </td>
            <td>
                @Html.TextAreaFor(model => model.Describe)
            </td>
        </tr>
    </table>*@
    <input id="btn_CreateComplaint" type ="submit" value="提交" />
}
@{
   if(Model!=null)
   {
       <table border="1px" bordercolor="#000000" cellspacing="0px" style="border-collapse:collapse">
           <tr>
               <td>
                   <strong>姓名</strong>
               </td>
               <td>
                   <strong>电话</strong>
               </td>
               <td>
                   <strong>Email</strong>
               </td>
               <td>
                   <strong>投诉地域</strong>
               </td>
               <td>
                   <strong>投诉类别</strong>
               </td>
               <td>
                   <strong>投诉方式</strong>
               </td>
               <td>
                   <strong>投诉时间</strong>
               </td>
               <td>
                   <strong>操作</strong>
               </td>
           </tr>
            @foreach (var item in Model)
            {
                <tr>
                <td>@item.ComplainerName</td>
                <td>@item.Phone</td>
                <td>@item.Email</td>
                <td>@item.Area</td>
                <td>@item.Class</td>
                <td>@item.Way</td>
                <td>@item.Date.ToShortDateString()</td>
                <td>@Html.ActionLink("查看详情","GetComplaintDetailByID", new { ID = item.ID})</td>
                </tr>
            }
       </table>
   }
}