Code/CustomerComplaintsSystem/Neusoft.CCS.WebUI/Areas/RVASS/Controllers/ImportantEventStaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Neusoft.CCS.Services.Implementation;
using Neusoft.CCS.Services.Interfaces;
using Neusoft.CCS.Services.ViewModels;
using Neusoft.CCS.Services.Mappings;
using Neusoft.CCS.Services.Messages;

namespace Neusoft.CCS.WebUI.Areas.RVASS.Controllers
{
    public class ImportantEventStaffController : Controller
    {
        //
        // GET: /RVASS/ImportantEventStaff/

        /// <summary>
        /// 重大事件（员工）处理单列表
        /// </summary>
        /// <returns></returns>
        public ActionResult ImportantEventBox()
        {
            var response = DI.SpringHelper.GetObject<IImptEvtStaffService>("ImptEvtStaffService").LoadingImptEventBoxForStaff();//staffId
            return View(response);
        }


        [HttpGet]
        public ActionResult ImportantEventHandled(int id)
        {
            var response = DI.SpringHelper.GetObject<IImptEvtStaffService>("ImptEvtStaffService").LoadingImptEvtStaffForm(id);
            return View(response);
        }

        [HttpPost]
        public ActionResult ImportantEventHandled(LoadingImptEvtStaffFormResponse model)
        {
            if (!DI.SpringHelper.GetObject<IImptEvtStaffService>("ImptEvtStaffService").ImptEvtHandled(model.ImptEvtStaffForm))
            {
                Response.Write("<script>alert('提交部门间职责信息失败！')</script>");
            }

            return RedirectToAction("ImportantEventBox", "ImportantEventDepartment");
        }

    }
}

Code/CustomerComplaintsSystem/Neusoft.CCS.WebUI/Areas/RVASS/Views/ImportantEventStaff/ImportantEventBox.cshtml
@{
    ViewBag.Title = "ImportantEventBox";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using Neusoft.CCS.Services.ViewModels; @*导入视图模型所在命名空间*@
@using Neusoft.CCS.Services.Messages;@*导入SOA基本模式“请求-相应”模型消息所在命名空间*@

@section title{
重大事件列表
}

@*@model Dictionary<int, ComplaintInfoOverviewViewModel>*@
@model LoadingImptEventBoxForStaffResponse

@if (Model.IsSuccess)
{
    <table border="1px">
    <tr>
        <th>投诉业务</th>
        <th>投诉客户</th>
        <th>投诉时间</th>
        <th>投诉方式</th>
        <th>操作</th>
    </tr>
    @foreach (var item in Model.ImptEventBoxForStaff)
    {
        <tr>
            <td>@item.Value.BusinessName</td>
            <td>@item.Value.ComplainerName</td>
            <td>@item.Value.Date</td>
            <td>@item.Value.Way</td>
            <td>@Html.ActionLink("处理", "ImportantEventHandled", new { id = item.Key })</td>
        </tr>
    }
</table>
}
else
{
    <text>@Model.ErrorMessage</text>
}

Code/CustomerComplaintsSystem/Neusoft.CCS.WebUI/Areas/RVASS/Views/ImportantEventStaff/ImportantEventHandled.cshtml
@{
    ViewBag.Title = "ImportantEventHandled";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using Neusoft.CCS.Services.ViewModels; @*导入视图模型所在命名空间*@
@using Neusoft.CCS.Services.Messages;@*导入SOA基本模式“请求-相应”模型消息所在命名空间*@

@*指定该页面模型的类型*@
@model Neusoft.CCS.Services.Messages.LoadingImptEvtStaffFormResponse

@section title{
    重大事件处理
}

@*客户端模型验证脚本开启*@
@{Html.EnableClientValidation(true);}

@if (Model.IsSuccess)
{
    using (Html.BeginForm("ImportantEventHandled", "ImportantEventStaff", FormMethod.Post))
    {
        <table border="1px">
            @Html.HiddenFor(s => s.ImptEvtStaffForm.CaseID)
            @Html.HiddenFor(s => s.ImptEvtStaffForm.ImptEvtStaffID)
            @Html.HiddenFor(s => s.ImptEvtStaffForm.BeginTime)
            <tr>
                <td>@Html.LabelFor(s => s.ImptEvtStaffForm.ComplaintDate)</td>
                <td>@Model.ImptEvtStaffForm.ComplaintDate</td>
            </tr>

            <tr>
                <td>@Html.LabelFor(s => s.ImptEvtStaffForm.Class)</td>
                <td>@Model.ImptEvtStaffForm.Class</td>
            </tr>

            <tr>
                <td>@Html.LabelFor(s => s.ImptEvtStaffForm.Describe)</td>
                <td>@Model.ImptEvtStaffForm.Describe</td>
            </tr>

            <tr>
                <td>@Html.LabelFor(s => s.ImptEvtStaffForm.Name)</td>
                <td>@Model.ImptEvtStaffForm.Name</td>
            </tr>

            <tr>
                <td>@Html.LabelFor(s => s.ImptEvtStaffForm.Satisfaction)</td>
                <td>@Model.ImptEvtStaffForm.Satisfaction</td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(s => s.ImptEvtStaffForm.ReturnVisitContent)
                </td>
                <td>
                    @Model.ImptEvtStaffForm.ReturnVisitContent
                </td>
            </tr>


            <tr>
                <td>
                    @Html.LabelFor(s => s.ImptEvtStaffForm.ComplaintReason)
                </td>
                <td>
                    @Model.ImptEvtStaffForm.ComplaintReason
                </td>
            </tr>


            <tr>
                <td>
                    @Html.LabelFor(s => s.ImptEvtStaffForm.Content)
                </td>
                <td>
                    @Html.EditorFor(s => s.ImptEvtStaffForm.Content)
                </td>
            </tr>




            <tr>
                <td colspan="2" align="right">
                    @*按钮没有相应的HtmlHelper方法，故必须自己写*@
                    <input type="submit" id="btnSure" value="提 交" />
                    <input type="reset" id="btnCancel" value="取 消" />
                </td>
            </tr>

        </table>
    }
}
else
{
    <text>@Model.ErrorMessage</text>
}